services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: vmemo
      POSTGRES_PASSWORD: vmemo
      POSTGRES_DB: vmemo
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  # web:
  #   build: .
  #   ports:
  #     - "3000:3000" 
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   environment:
  #     - DATABASE_URL=postgres://vmemo:vmemo@postgres:5432/vmemo
  #   depends_on:
  #     - postgres
volumes:
  db:
